name: SimpleHomes
version: 2.2
author: nijabutter
main: nijabutter.SimpleHomes
description: Simple homes plugin

permissions:
  homes.*:
    description: SimpleHomes
    children:
      homes.skipwait: true
      homes.bypasscap: true
      homes.admin: true
    homes.skipwait:
      description: Skip the countdown
      default: op
    homes.bypasscap:
      description: Bypass the maximum homes cap
      default: op
    homes.admin:
      description: Manage other player homes
      default: op


commands:
  homes:
    description: Displays your currently set homes
    usage: /homes
    alises: [listhomes, hms]
  sethome:
    description: Set a new home at your current location
    usage: /sethome <name>
    aliases: [newhome, createhome, makehome, shome, nhome, shm, nhm]
  delhome:
    description: Delete a home
    usage: /delhome <name>
    aliases: [rmhome, dhome, rhome, deletehome, removehome]
  home:
    description: Teleport to a home
    usage: /home <name>